"""
api.py — FastAPI backend for Folsom AQI Forecast.
Loads all 12 models once at startup. Serves cached forecasts — never runs
ML models inline on a web request.

Start with: uvicorn api:app --host 0.0.0.0 --port 8000
"""

import json
import sys
from contextlib import asynccontextmanager
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

load_dotenv()  # Load .env file (AIRNOW_API_KEY etc.)

from inference import load_all_models, predict_now, load_cached_forecast, cache_age_minutes

# ─── CORS ─────────────────────────────────────────────────────────────────────

# Track startup time for health endpoint
_startup_time: str = ""
_models_loaded: bool = False


# ─── Lifespan ─────────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Load all 12 models and imputers into memory at startup.
    This is the only time we touch the disk for model files.
    Keeps per-request latency < 200ms.
    """
    # ── V9 Optimization ───────────────────────────────────────────────────────
    # The FastAPI server NO LONGER pre-loads the 12 LightGBM models into RAM.
    # Because Render is memory-constrained (512MB) and the /forecast endpoint 
    # explicitly fetches the CDN JSON generated by GitHub Actions, holding
    # the 20,000-tree models in memory causes an R14 OOM loop for no benefit.
    
    _models_loaded = False
    print("[api] Running in CDN-proxy mode. ML inference handled by external worker.", file=sys.stderr)
    yield
    # ──────────────────────────────────────────────────────────────────────────
    # (no shutdown cleanup needed)


# ─── App setup ────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Folsom AQI Forecast API",
    description="Real-time AQI forecast for Folsom, CA using LightGBM + Open-Meteo",
    version="1.0.0",
    lifespan=lifespan,
)

# Allow all origins so the Streamlit Cloud frontend can call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


# ─── Endpoints ────────────────────────────────────────────────────────────────

@app.get("/")
async def root():
    """
    Root endpoint. Returns a simple welcome message since all actual
    API logic is under specific routes (like /forecast or /health).
    """
    return {
        "message": "Folsom AQI Forecast API is running.",
        "status_endpoint": "/health",
        "doc_endpoint": "/docs"
    }


@app.get("/health")
async def health():
    """
    Health check. Returns model load status and last refresh time.
    Used by deploy.sh to verify the service is up.
    """
    # FIXED: Force remote CDN fetch
    cached = load_cached_forecast(prefer_remote=True)
    last_refresh = cached.get("generated_at", "never") if cached else "never"

    return {
        "status":        "ok",
        "models_loaded": _models_loaded,
        "startup_time":  _startup_time,
        "last_refresh":  last_refresh,
        "cache_age_minutes": cache_age_minutes(),
    }


@app.get("/forecast")
async def get_forecast():
    """
    Return the cached AQI forecast JSON.
    Always pulls from the GitHub CDN (data-cache branch) to bypass
    Render IP rate limits.
    """
    cached = load_cached_forecast(prefer_remote=True)
    if cached is None:
        raise HTTPException(status_code=503, detail="No forecast data available from CDN or local cache.")

    return JSONResponse(content=cached)


@app.get("/refresh")
async def trigger_refresh():
    """
    Manually trigger a forecast fetch from the CDN.
    Note: Live recalculation is disabled on Render to avoid 429s.
    Recalculation happens automatically via GitHub Actions every hour.
    """
    try:
        result = load_cached_forecast(prefer_remote=True)
        if not result:
            raise RuntimeError("Could not fetch remote cache.")
        return {
            "refreshed":      True,
            "source":         "GitHub CDN (data-cache)",
            "generated_at":   result.get("generated_at"),
            "data_freshness": result.get("data_freshness_minutes"),
        }
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Remote refresh failed: {exc}")


@app.get("/current")
async def get_current():
    """
    Return only the current AQI reading (subset of /forecast).
    Lightweight endpoint for simple widgets.
    """
    # FIXED: Force remote CDN fetch
    cached = load_cached_forecast(prefer_remote=True)
    if not cached:
        raise HTTPException(status_code=503, detail="No forecast data available yet.")
    return {
        "current":      cached.get("current"),
        "generated_at": cached.get("generated_at"),
        "location":     cached.get("location"),
    }


@app.get("/history")
async def get_history():
    """
    Return the 72-hour history array (actual vs forecast).
    Used by the dashboard to draw the comparison chart.
    """
    # FIXED: Force remote CDN fetch
    cached = load_cached_forecast(prefer_remote=True)
    if not cached:
        raise HTTPException(status_code=503, detail="No forecast data available yet.")
    return {
        "history_72h":  cached.get("history_72h", []),
        "generated_at": cached.get("generated_at"),
    }
